### PR TITLE
Create compile.yml

### PR DESCRIPTION
**Pull request by zac-garby**
does it work? oh the mystery

### CODE REVIEW

**Comment by Emersont1** [comment]
can we have it comment it to the PR?

**Comment by zac-garby** [comment]
how do i do that?

**Comment by zac-garby** [comment]
let's merge this just to see if it even works then i'll try and do that later on. i've got to go out at 2 anyway

**Comment by Emersont1** [comment]
https://github.community/t/making-links-to-artifacts-available-from-pull-requests/18236/2

**Comment by zac-garby** [comment]
oh ok, looks simple enough. i'll do that later

**Review by Emersont1 — APPROVED** [review]

**Pull request merged**
