### PR TITLE
add sources

### PR DESCRIPTION
**Pull request by zac-garby**

### CODE REVIEW

**Comment by Emersont1** [comment]
the template doesn't use a.) so we may as well remove that
i think it needs CI

**Comment by zac-garby** [comment]
"doesn't use a.)" wdym?

i'll do the CI afterwards

**Comment by Emersont1** [comment]
like the template goes
1
1.1
1.1.1
 the a) part was just because i put it in GDocs

**Comment by zac-garby** [comment]
so should, for example, president be "4.2.1"? or "4.ii.i"? i quite like it like this tbh

**Comment by Emersont1** [comment]
I think 4.2.1 is more in keeping with the Union's style

**Comment by zac-garby** [comment]
ok done

**Review by Emersont1 — APPROVED** [review]

**Pull request merged**
